apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-webapp-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ip-hw3"
  labels:
    name: nginx-webapp-ingress
spec:
  rules:
    - host: app.atnk-studentsurvey.com
      http:
        paths:
        - path: /qwe
          pathType: ImplementationSpecific
          backend:
            service:
              name: nginx-hello-worlds-svc
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: myapp-svc
              port:
                number: 8080