apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: myapp-ingress
    annotations:
        kubernetes.io/ingress.global-static-ip-name: "ip-hw3"
    labels:
        name: myapp-ingress
spec:
    defaultBackend:
        service:
            name: nginx-hello-worlds-svc
            port:
                number: 80
    rules:
        - host: app.atnk-studentsurvey.com
          http:
              paths:
              - path: /survey
                pathType: Prefix
                backend:
                  service:
                    name: nginx-hello-worlds-svc
                  port:
                      number: 80